## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

branches:
  except:
    - dev
    - /^dev-.*$/
    - /^dev_.*$/

os:
  - linux
  - osx
julia:
  - 1.1
  - nightly

addons:
  apt:
    packages:
      - python3-scipy

codecov: false
coveralls: true

# Allow to fail on nightly
matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false
