branches:
  only:
    # Only build master and version tags
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    # For Bors:
    - staging
    - trying

language: julia
cache:
  directories:
  - $HOME/.julia/artifacts

env:
  global:
    - PYTHON=""  # Force using Conda in PyCall
install: |       # Install conda dependencies
  julia -e '
    using Pkg; Pkg.add("Conda"); using Conda
    Conda.add(["blas=*=*netlib", "nomkl", "ase"]; channel="conda-forge")
  '
after_success: |  # Upload coverage when things are good.
  julia -e '
    using Pkg; Pkg.add("Coverage"); using Coverage
    coverage = Coveralls.process_folder()
    for excluded in ["src/FourierTransforms.jl", "src/eigen/diag_lobpcg_itsolve.jl"]
        filter!(c -> !occursin(excluded, c.filename), coverage)
    end
    Coveralls.submit(coverage)
  '

julia: "1.4"
os: linux

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/675ffcbb101b5d1a3424
    on_success: always
    on_failure: always
