branches:
  only:
    # Only build master and version tags
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

dist: bionic
os:
  - linux
  - osx
language: julia
julia:
  - 1.1
  - nightly

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

matrix:
  allow_failures:  # Allow to fail on nightly
    - julia: nightly
  exclude:
    - os: osx
      julia: nightly

install: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip3 install spglib scipy pymatgen
  else
     :
  fi

codecov: false
coveralls: true

# Build documentation
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

after_failure: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      python3 --version
      pip3 list
  fi

notifications:
  email: false
