## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

branches:
  only:
    # Only build master and version tags
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

os:
  - linux
# Something is seriously wrong with the lobpcg from scipy on MacOS
#    => MacOS stays disabled for now
#  - osx
julia:
  - 1.1
  - nightly

addons:
  apt:
    packages:
      - python3-scipy

codecov: false
coveralls: true

# Allow to fail on nightly
matrix:
  allow_failures:
  - julia: nightly


# Build documentation
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

notifications:
  email: false
