indent = 4
margin = 94
style = "blue"
always_for_in = false
whitespace_typedefs = true
whitespace_ops_in_indices = false
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = true
short_to_long_function_def = false
always_use_return = false
whitespace_in_kwargs = false
annotate_untyped_fields_with_any = false
format_docstrings  = false
align_struct_field = true
align_conditional  = true
align_assignment   = true
align_pair_arrow   = true
